package com.epic.tle.mapping;
// Generated Jun 1, 2017 10:53:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EpicTleNii generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_NII"
//    ,catalog="epictle_v5ch"
)
public class EpicTleNii  implements java.io.Serializable {


     private Integer id;
     private String nii;
     private String mapNii;
     private Date datetime;
     private int channelid;
     private Integer tlestatus;
     private EpicTleNodetype epicTleNodetype;

     

    public EpicTleNii() {
    }

	
    public EpicTleNii(String nii, String mapNii, Date datetime, int channelid) {
        this.nii = nii;
        this.mapNii = mapNii;
        this.datetime = datetime;
        this.channelid = channelid;
    }
    public EpicTleNii(String nii, String mapNii, Date datetime, int channelid, Integer tlestatus) {
       this.nii = nii;
       this.mapNii = mapNii;
       this.datetime = datetime;
       this.channelid = channelid;
       this.tlestatus = tlestatus;
    }
   
    @Id
    @GenericGenerator(name = "id_generator", strategy = "com.epic.tle.util.IdGenerator", parameters= {@Parameter(name="columnPram", value = "id")})
    @GeneratedValue(generator = "id_generator") 
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NODE", nullable=false)
    public EpicTleNodetype getEpicTleNodetype() {
        return this.epicTleNodetype;
    }
    
    public void setEpicTleNodetype(EpicTleNodetype epicTleNodetype) {
        this.epicTleNodetype = epicTleNodetype;
    }
    
    @Column(name="NII", nullable=false, length=3)
    public String getNii() {
        return this.nii;
    }
    
    public void setNii(String nii) {
        this.nii = nii;
    }

    
    @Column(name="MAP_NII", nullable=false, length=3)
    public String getMapNii() {
        return this.mapNii;
    }
    
    public void setMapNii(String mapNii) {
        this.mapNii = mapNii;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", nullable=false, length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="CHANNELID", nullable=false)
    public int getChannelid() {
        return this.channelid;
    }
    
    public void setChannelid(int channelid) {
        this.channelid = channelid;
    }

    
    @Column(name="TLESTATUS")
    public Integer getTlestatus() {
        return this.tlestatus;
    }
    
    public void setTlestatus(Integer tlestatus) {
        this.tlestatus = tlestatus;
    }

    @Override
    public String toString() {
       try{
            return "{" + "Id:" + id + ", NII:" + nii + ", Map Nii:" + mapNii  + ", C hannelid:" + channelid + ", Status:" + tlestatus + ", Node type:" + epicTleNodetype.getCode() + '}';
        }
        catch(Exception e){
            return "{" + "Id:" + id + ", NII:" + nii + ", Map Nii:" + mapNii  + ", Channel id:" + channelid + ", Status:" + tlestatus + '}';
        }
    }
    
    public String forHistory() {
        try{
            return "{" + "Id:" + id + ", NII:" + nii + ", Map Nii:" + mapNii  + ", C hannelid:" + channelid + ", Status:" + tlestatus + ", Node type:" + epicTleNodetype.getCode() + '}';
        }
        catch(Exception e){
            return "{" + "Id:" + id + ", NII:" + nii + ", Map Nii:" + mapNii  + ", Channel id:" + channelid + ", Status:" + tlestatus + '}';
        }
    }




}


