package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpicTleSysOperation generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_SYS_OPERATION"
//    ,catalog="epictle_v5ch"
)
public class EpicTleSysOperation  implements java.io.Serializable {


     private int code;
     private EpicTleColorFormat epicTleColorFormat;
     private EpicTleStatus epicTleStatus;
     private String description;
     private Date datetime;
     private String message;
     private Set<EpicTleOperationAlerts> epicTleOperationAlertses = new HashSet<EpicTleOperationAlerts>(0);

    public EpicTleSysOperation() {
    }

	
    public EpicTleSysOperation(int code) {
        this.code = code;
    }
    public EpicTleSysOperation(int code, EpicTleColorFormat epicTleColorFormat, EpicTleStatus epicTleStatus, String description, Date datetime, String message, Set<EpicTleOperationAlerts> epicTleOperationAlertses) {
       this.code = code;
       this.epicTleColorFormat = epicTleColorFormat;
       this.epicTleStatus = epicTleStatus;
       this.description = description;
       this.datetime = datetime;
       this.message = message;
       this.epicTleOperationAlertses = epicTleOperationAlertses;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COLOR")
    public EpicTleColorFormat getEpicTleColorFormat() {
        return this.epicTleColorFormat;
    }
    
    public void setEpicTleColorFormat(EpicTleColorFormat epicTleColorFormat) {
        this.epicTleColorFormat = epicTleColorFormat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public EpicTleStatus getEpicTleStatus() {
        return this.epicTleStatus;
    }
    
    public void setEpicTleStatus(EpicTleStatus epicTleStatus) {
        this.epicTleStatus = epicTleStatus;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATETIME", length=19)
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    
    @Column(name="MESSAGE", length=45)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleSysOperation")
    public Set<EpicTleOperationAlerts> getEpicTleOperationAlertses() {
        return this.epicTleOperationAlertses;
    }
    
    public void setEpicTleOperationAlertses(Set<EpicTleOperationAlerts> epicTleOperationAlertses) {
        this.epicTleOperationAlertses = epicTleOperationAlertses;
    }

    @Override
    public String toString() {
        return "EpicTleSysOperation{" + "code=" + code + ", epicTleColorFormat=" + epicTleColorFormat.getCode() + ", epicTleStatus=" + epicTleStatus.getCode() + ", description=" + description + ", datetime=" + datetime + ", message=" + message + ", epicTleOperationAlertses=" + epicTleOperationAlertses + '}';
    }




}


