package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleTask generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_TASK"
//    ,catalog="epictle_v5ch"
)
public class EpicTleTask  implements java.io.Serializable {


     private String taskId;
     private String description;
     private Set<EpicTleSection> epicTleSections = new HashSet<EpicTleSection>(0);
     private Set<EpicTleHistory> epicTleHistories = new HashSet<EpicTleHistory>(0);
     private Set<EpicTleProfilePrivilage> epicTleProfilePrivilages = new HashSet<EpicTleProfilePrivilage>(0);

    public EpicTleTask() {
    }

	
    public EpicTleTask(String taskId) {
        this.taskId = taskId;
    }
    public EpicTleTask(String taskId, String description, Set<EpicTleSection> epicTleSections, Set<EpicTleHistory> epicTleHistories, Set<EpicTleProfilePrivilage> epicTleProfilePrivilages) {
       this.taskId = taskId;
       this.description = description;
       this.epicTleSections = epicTleSections;
       this.epicTleHistories = epicTleHistories;
       this.epicTleProfilePrivilages = epicTleProfilePrivilages;
    }
   
     @Id 

    
    @Column(name="TASK_ID", unique=true, nullable=false, length=2)
    public String getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    
    @Column(name="DESCRIPTION", length=20)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="epicTleTasks")
    public Set<EpicTleSection> getEpicTleSections() {
        return this.epicTleSections;
    }
    
    public void setEpicTleSections(Set<EpicTleSection> epicTleSections) {
        this.epicTleSections = epicTleSections;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleTask")
    public Set<EpicTleHistory> getEpicTleHistories() {
        return this.epicTleHistories;
    }
    
    public void setEpicTleHistories(Set<EpicTleHistory> epicTleHistories) {
        this.epicTleHistories = epicTleHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleTask")
    public Set<EpicTleProfilePrivilage> getEpicTleProfilePrivilages() {
        return this.epicTleProfilePrivilages;
    }
    
    public void setEpicTleProfilePrivilages(Set<EpicTleProfilePrivilage> epicTleProfilePrivilages) {
        this.epicTleProfilePrivilages = epicTleProfilePrivilages;
    }

    @Override
    public String toString() {
        return "EpicTleTask{" + "taskId=" + taskId + ", description=" + description + ", epicTleSections=" + epicTleSections + ", epicTleHistories=" + epicTleHistories + ", epicTleProfilePrivilages=" + epicTleProfilePrivilages + '}';
    }




}


