package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EpicTleStatusofresponse generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_STATUSOFRESPONSE"
//    ,catalog="epictle_v5ch"
)
public class EpicTleStatusofresponse  implements java.io.Serializable {


     private int fieldno;
     private EpicTleStatus epicTleStatus;

    public EpicTleStatusofresponse() {
    }

    public EpicTleStatusofresponse(int fieldno, EpicTleStatus epicTleStatus) {
       this.fieldno = fieldno;
       this.epicTleStatus = epicTleStatus;
    }
   
     @Id 

    
    @Column(name="FIELDNO", unique=true, nullable=false)
    public int getFieldno() {
        return this.fieldno;
    }
    
    public void setFieldno(int fieldno) {
        this.fieldno = fieldno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public EpicTleStatus getEpicTleStatus() {
        return this.epicTleStatus;
    }
    
    public void setEpicTleStatus(EpicTleStatus epicTleStatus) {
        this.epicTleStatus = epicTleStatus;
    }

    @Override
    public String toString() {
        return  " fieldno " + fieldno + ": status = " + epicTleStatus.getCode()+" " ;
    }
    public String forHistory() {
        return " fieldno " + fieldno + ": status = " + epicTleStatus.getCode() ;
    }




}


