package com.epic.tle.mapping;
// Generated Aug 28, 2017 1:57:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleNodetype generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_NODETYPE"
//    ,catalog="epictle_v5ch"
)
public class EpicTleNodetype  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleNii> epicTleNiis = new HashSet<EpicTleNii>(0);
     private Set<EpicTleProcessingTime> epicTleProcessingTimes = new HashSet<EpicTleProcessingTime>(0);
     private Set<EpicTleListeners> epicTleListenerses = new HashSet<EpicTleListeners>(0);
     private Set<EpicTleOperationAlerts> epicTleOperationAlertses = new HashSet<EpicTleOperationAlerts>(0);
     private Set<EpicTleHistory> epicTleHistories = new HashSet<EpicTleHistory>(0);
     private Set<EpicTleChannel> epicTleChannels = new HashSet<EpicTleChannel>(0);
     private Set<EpicTleAlerts> epicTleAlertses = new HashSet<EpicTleAlerts>(0);

    public EpicTleNodetype() {
    }

	
    public EpicTleNodetype(int code) {
        this.code = code;
    }
    public EpicTleNodetype(int code, String description, Set<EpicTleNii> epicTleNiis, Set<EpicTleProcessingTime> epicTleProcessingTimes, Set<EpicTleListeners> epicTleListenerses, Set<EpicTleOperationAlerts> epicTleOperationAlertses, Set<EpicTleHistory> epicTleHistories, Set<EpicTleChannel> epicTleChannels, Set<EpicTleAlerts> epicTleAlertses) {
       this.code = code;
       this.description = description;
       this.epicTleNiis = epicTleNiis;
       this.epicTleProcessingTimes = epicTleProcessingTimes;
       this.epicTleListenerses = epicTleListenerses;
       this.epicTleOperationAlertses = epicTleOperationAlertses;
       this.epicTleHistories = epicTleHistories;
       this.epicTleChannels = epicTleChannels;
       this.epicTleAlertses = epicTleAlertses;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=10)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleNii> getEpicTleNiis() {
        return this.epicTleNiis;
    }
    
    public void setEpicTleNiis(Set<EpicTleNii> epicTleNiis) {
        this.epicTleNiis = epicTleNiis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleProcessingTime> getEpicTleProcessingTimes() {
        return this.epicTleProcessingTimes;
    }
    
    public void setEpicTleProcessingTimes(Set<EpicTleProcessingTime> epicTleProcessingTimes) {
        this.epicTleProcessingTimes = epicTleProcessingTimes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleListeners> getEpicTleListenerses() {
        return this.epicTleListenerses;
    }
    
    public void setEpicTleListenerses(Set<EpicTleListeners> epicTleListenerses) {
        this.epicTleListenerses = epicTleListenerses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleOperationAlerts> getEpicTleOperationAlertses() {
        return this.epicTleOperationAlertses;
    }
    
    public void setEpicTleOperationAlertses(Set<EpicTleOperationAlerts> epicTleOperationAlertses) {
        this.epicTleOperationAlertses = epicTleOperationAlertses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleHistory> getEpicTleHistories() {
        return this.epicTleHistories;
    }
    
    public void setEpicTleHistories(Set<EpicTleHistory> epicTleHistories) {
        this.epicTleHistories = epicTleHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleChannel> getEpicTleChannels() {
        return this.epicTleChannels;
    }
    
    public void setEpicTleChannels(Set<EpicTleChannel> epicTleChannels) {
        this.epicTleChannels = epicTleChannels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleNodetype")
    public Set<EpicTleAlerts> getEpicTleAlertses() {
        return this.epicTleAlertses;
    }
    
    public void setEpicTleAlertses(Set<EpicTleAlerts> epicTleAlertses) {
        this.epicTleAlertses = epicTleAlertses;
    }

    @Override
    public String toString() {
        return "EpicTleNodetype{" + "code=" + code + ", description=" + description + ", epicTleNiis=" + epicTleNiis + ", epicTleProcessingTimes=" + epicTleProcessingTimes + ", epicTleListenerses=" + epicTleListenerses + ", epicTleOperationAlertses=" + epicTleOperationAlertses + ", epicTleHistories=" + epicTleHistories + ", epicTleChannels=" + epicTleChannels + ", epicTleAlertses=" + epicTleAlertses + '}';
    }




}


