package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleConnectiontypes generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_CONNECTIONTYPES"
//    ,catalog="epictle_v5ch"
)
public class EpicTleConnectiontypes  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleListeners> epicTleListenerses = new HashSet<EpicTleListeners>(0);

    public EpicTleConnectiontypes() {
    }

	
    public EpicTleConnectiontypes(int code, String description) {
        this.code = code;
        this.description = description;
    }
    public EpicTleConnectiontypes(int code, String description, Set<EpicTleListeners> epicTleListenerses) {
       this.code = code;
       this.description = description;
       this.epicTleListenerses = epicTleListenerses;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=15)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleConnectiontypes")
    public Set<EpicTleListeners> getEpicTleListenerses() {
        return this.epicTleListenerses;
    }
    
    public void setEpicTleListenerses(Set<EpicTleListeners> epicTleListenerses) {
        this.epicTleListenerses = epicTleListenerses;
    }

    @Override
    public String toString() {
        return "EpicTleConnectiontypes{" + "code=" + code + ", description=" + description + ", epicTleListenerses=" + epicTleListenerses + '}';
    }




}


