package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EpicTleUser generated by hbm2java
 */
@Entity
@Table(name = "EPIC_TLE_USER_PASSWORD_HISTORY"
//    ,catalog="epictle_v5ch"
)
public class EpicTleUserPasswordHistory implements java.io.Serializable {

    private Integer passwordHistoryId;
    private String privousPassword;
    private EpicTleUser userId;
    private Date createdDate;

    public EpicTleUserPasswordHistory() {
    }

    public EpicTleUserPasswordHistory(Integer passwordHistoryId, String privousPassword, EpicTleUser userId, Date createdDate) {
        this.passwordHistoryId = passwordHistoryId;
        this.privousPassword = privousPassword;
        this.userId = userId;
        this.createdDate = createdDate;
    }

    @Id
    @GenericGenerator(name = "id_generator", strategy = "com.epic.tle.util.IdGenerator", parameters= {@Parameter(name="columnPram", value = "passwordHistoryId")})
    @GeneratedValue(generator = "id_generator")
    @Column(name = "PASSWORD_HISTORY_ID", unique = true, nullable = false)
    public Integer getPasswordHistoryId() {
        return passwordHistoryId;
    }

    public void setPasswordHistoryId(Integer passwordHistoryId) {
        this.passwordHistoryId = passwordHistoryId;
    }

    @Column(name = "PREVIOUS_PASSWORD", length = 255)
    public String getPrivousPassword() {
        return privousPassword;
    }

    public void setPrivousPassword(String privousPassword) {
        this.privousPassword = privousPassword;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USERID")
    public EpicTleUser getUserId() {
        return userId;
    }

    public void setUserId(EpicTleUser userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CERATED_DATE", length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public String toString() {
        return "EpicTleUserPasswordHistory{" + "passwordHistoryId=" + passwordHistoryId + ", privousPassword=" + privousPassword + ", userId=" + userId + ", createdDate=" + createdDate + '}';
    }
    

}
