package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleForwardmethod generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_FORWARDMETHOD"
//    ,catalog="epictle_v5ch"
)
public class EpicTleForwardmethod  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleChannel> epicTleChannels = new HashSet<EpicTleChannel>(0);

    public EpicTleForwardmethod() {
    }

	
    public EpicTleForwardmethod(int code) {
        this.code = code;
    }
    public EpicTleForwardmethod(int code, String description, Set<EpicTleChannel> epicTleChannels) {
       this.code = code;
       this.description = description;
       this.epicTleChannels = epicTleChannels;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=15)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleForwardmethod")
    public Set<EpicTleChannel> getEpicTleChannels() {
        return this.epicTleChannels;
    }
    
    public void setEpicTleChannels(Set<EpicTleChannel> epicTleChannels) {
        this.epicTleChannels = epicTleChannels;
    }

    @Override
    public String toString() {
        return "EpicTleForwardmethod{" + "code=" + code + ", description=" + description + ", epicTleChannels=" + epicTleChannels + '}';
    }




}


