package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleHeaderFormats generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_HEADER_FORMATS"
//    ,catalog="epictle_v5ch"
)
public class EpicTleHeaderFormats  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleListeners> epicTleListenerses = new HashSet<EpicTleListeners>(0);
     private Set<EpicTleChannel> epicTleChannels = new HashSet<EpicTleChannel>(0);

    public EpicTleHeaderFormats() {
    }

	
    public EpicTleHeaderFormats(int code) {
        this.code = code;
    }
    public EpicTleHeaderFormats(int code, String description, Set<EpicTleListeners> epicTleListenerses, Set<EpicTleChannel> epicTleChannels) {
       this.code = code;
       this.description = description;
       this.epicTleListenerses = epicTleListenerses;
       this.epicTleChannels = epicTleChannels;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleHeaderFormats")
    public Set<EpicTleListeners> getEpicTleListenerses() {
        return this.epicTleListenerses;
    }
    
    public void setEpicTleListenerses(Set<EpicTleListeners> epicTleListenerses) {
        this.epicTleListenerses = epicTleListenerses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleHeaderFormats")
    public Set<EpicTleChannel> getEpicTleChannels() {
        return this.epicTleChannels;
    }
    
    public void setEpicTleChannels(Set<EpicTleChannel> epicTleChannels) {
        this.epicTleChannels = epicTleChannels;
    }

    @Override
    public String toString() {
        return "EpicTleHeaderFormats{" + "code=" + code + ", description=" + description + ", epicTleListenerses=" + epicTleListenerses + ", epicTleChannels=" + epicTleChannels + '}';
    }




}


