package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EpicTleEsmodule generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_ESMODULE"
//    ,catalog="epictle_v5ch"
)
public class EpicTleEsmodule  implements java.io.Serializable {


     private String esm;
     private EpicTleStatus epicTleStatus;
     private String elmk;
     private String lmkkvc;
     private String etmk;
     private String tmkkvc;
     private String emek;
     private String mekkvc;
     private String efwk;
     private String fwkkvc;

    public EpicTleEsmodule() {
    }

	
    public EpicTleEsmodule(String esm) {
        this.esm = esm;
    }
    public EpicTleEsmodule(String esm, EpicTleStatus epicTleStatus, String elmk, String lmkkvc, String etmk, String tmkkvc, String emek, String mekkvc, String efwk, String fwkkvc) {
       this.esm = esm;
       this.epicTleStatus = epicTleStatus;
       this.elmk = elmk;
       this.lmkkvc = lmkkvc;
       this.etmk = etmk;
       this.tmkkvc = tmkkvc;
       this.emek = emek;
       this.mekkvc = mekkvc;
       this.efwk = efwk;
       this.fwkkvc = fwkkvc;
    }
   
     @Id 

    
    @Column(name="ESM", unique=true, nullable=false, length=5)
    public String getEsm() {
        return this.esm;
    }
    
    public void setEsm(String esm) {
        this.esm = esm;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public EpicTleStatus getEpicTleStatus() {
        return this.epicTleStatus;
    }
    
    public void setEpicTleStatus(EpicTleStatus epicTleStatus) {
        this.epicTleStatus = epicTleStatus;
    }

    
    @Column(name="ELMK", length=32)
    public String getElmk() {
        return this.elmk;
    }
    
    public void setElmk(String elmk) {
        this.elmk = elmk;
    }

    
    @Column(name="LMKKVC", length=6)
    public String getLmkkvc() {
        return this.lmkkvc;
    }
    
    public void setLmkkvc(String lmkkvc) {
        this.lmkkvc = lmkkvc;
    }

    
    @Column(name="ETMK", length=32)
    public String getEtmk() {
        return this.etmk;
    }
    
    public void setEtmk(String etmk) {
        this.etmk = etmk;
    }

    
    @Column(name="TMKKVC", length=6)
    public String getTmkkvc() {
        return this.tmkkvc;
    }
    
    public void setTmkkvc(String tmkkvc) {
        this.tmkkvc = tmkkvc;
    }

    
    @Column(name="EMEK", length=32)
    public String getEmek() {
        return this.emek;
    }
    
    public void setEmek(String emek) {
        this.emek = emek;
    }

    
    @Column(name="MEKKVC", length=6)
    public String getMekkvc() {
        return this.mekkvc;
    }
    
    public void setMekkvc(String mekkvc) {
        this.mekkvc = mekkvc;
    }

    
    @Column(name="EFWK", length=32)
    public String getEfwk() {
        return this.efwk;
    }
    
    public void setEfwk(String efwk) {
        this.efwk = efwk;
    }

    
    @Column(name="FWKKVC", length=6)
    public String getFwkkvc() {
        return this.fwkkvc;
    }
    
    public void setFwkkvc(String fwkkvc) {
        this.fwkkvc = fwkkvc;
    }

    @Override
    public String toString() {
        return "EpicTleEsmodule{" + "esm=" + esm + ", epicTleStatus=" + epicTleStatus.getCode() + ", elmk=" + elmk + ", lmkkvc=" + lmkkvc + ", etmk=" + etmk + ", tmkkvc=" + tmkkvc + ", emek=" + emek + ", mekkvc=" + mekkvc + ", efwk=" + efwk + ", fwkkvc=" + fwkkvc + '}';
    }




}


