package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleTxntypes generated by hbm2java
 */
@Entity
@Table(name = "EPIC_TLE_TXNTYPES"
//        , catalog = "epictle_v5ch"
)
public class EpicTleTxntypes implements java.io.Serializable {

    private int code;
    private String description;
    private Set<EpicTleAlerts> epicTleAlertses = new HashSet<EpicTleAlerts>(0);
    private Set<EpicTleProcessingTime> epicTleProcessingTimes = new HashSet<EpicTleProcessingTime>(0);

    public EpicTleTxntypes() {
    }

    public EpicTleTxntypes(int code, String description) {
        this.code = code;
        this.description = description;
    }

    public EpicTleTxntypes(int code, String description, Set<EpicTleAlerts> epicTleAlertses,Set<EpicTleProcessingTime> epicTleProcessingTimes) {
        this.code = code;
        this.epicTleProcessingTimes=epicTleProcessingTimes;
        this.description = description;
        this.epicTleAlertses = epicTleAlertses;
    }

    @Id

    @Column(name = "CODE", unique = true, nullable = false)
    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 45)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "epicTleTxntypes")
    public Set<EpicTleAlerts> getEpicTleAlertses() {
        return this.epicTleAlertses;
    }

    public void setEpicTleAlertses(Set<EpicTleAlerts> epicTleAlertses) {
        this.epicTleAlertses = epicTleAlertses;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleTxntypes")
    public Set<EpicTleProcessingTime> getEpicTleProcessingTimes() {
        return this.epicTleProcessingTimes;
    }
    
    public void setEpicTleProcessingTimes(Set<EpicTleProcessingTime> epicTleProcessingTimes) {
        this.epicTleProcessingTimes = epicTleProcessingTimes;
    }

    @Override
    public String toString() {
        return "EpicTleTxntypes{" + "code=" + code + ", description=" + description + ", epicTleAlertses=" + epicTleAlertses + ", epicTleProcessingTimes=" + epicTleProcessingTimes + '}';
    }
    
    

}
