package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleReplayAttacklevel generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_REPLAY_ATTACKLEVEL"
//    ,catalog="epictle_v5ch"
)
public class EpicTleReplayAttacklevel  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleInitconfig> epicTleInitconfigs = new HashSet<EpicTleInitconfig>(0);

    public EpicTleReplayAttacklevel() {
    }

	
    public EpicTleReplayAttacklevel(int code) {
        this.code = code;
    }
    public EpicTleReplayAttacklevel(int code, String description, Set<EpicTleInitconfig> epicTleInitconfigs) {
       this.code = code;
       this.description = description;
       this.epicTleInitconfigs = epicTleInitconfigs;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleReplayAttacklevel")
    public Set<EpicTleInitconfig> getEpicTleInitconfigs() {
        return this.epicTleInitconfigs;
    }
    
    public void setEpicTleInitconfigs(Set<EpicTleInitconfig> epicTleInitconfigs) {
        this.epicTleInitconfigs = epicTleInitconfigs;
    }

    @Override
    public String toString() {
        return "EpicTleReplayAttacklevel{" + "code=" + code + ", description=" + description + ", epicTleInitconfigs=" + epicTleInitconfigs + '}';
    }
    
    

}


