package com.epic.tle.mapping;
// Generated Jun 1, 2017 10:53:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EpicTleIsoFormat generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_ISO_FORMAT"
//    ,catalog="epictle_v5ch"
    , uniqueConstraints = @UniqueConstraint(columnNames="EPIC_TLE_ISO_FORMAT") 
)
public class EpicTleIsoFormat  implements java.io.Serializable {


     private int code;
     private String epicTleIsoFormat;

    public EpicTleIsoFormat() {
    }

	
    public EpicTleIsoFormat(int code) {
        this.code = code;
    }
    public EpicTleIsoFormat(int code, String epicTleIsoFormat) {
       this.code = code;
       this.epicTleIsoFormat = epicTleIsoFormat;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="EPIC_TLE_ISO_FORMAT", unique=true, length=45)
    public String getEpicTleIsoFormat() {
        return this.epicTleIsoFormat;
    }
    
    public void setEpicTleIsoFormat(String epicTleIsoFormat) {
        this.epicTleIsoFormat = epicTleIsoFormat;
    }

    @Override
    public String toString() {
        return "EpicTleIsoFormat{" + "code=" + code + ", epicTleIsoFormat=" + epicTleIsoFormat + '}';
    }




}


