package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EpicTleBlockBin generated by hbm2java
 */
@Entity
@Table(name = "EPIC_TLE_BLOCK_BIN"
//    ,catalog="epictle_v5ch"
)
public class EpicTleBlockBin implements java.io.Serializable {

    private EpicTleBlockBinId id;
    private EpicTleBinProfile epicTleBinProfile;
    private Date datetime;

    public EpicTleBlockBin() {
    }

    public EpicTleBlockBin(EpicTleBlockBinId id, EpicTleBinProfile epicTleBinProfile) {
        this.id = id;
        this.epicTleBinProfile = epicTleBinProfile;
    }

    public EpicTleBlockBin(EpicTleBlockBinId id, EpicTleBinProfile epicTleBinProfile, Date datetime) {
        this.id = id;
        this.epicTleBinProfile = epicTleBinProfile;
        this.datetime = datetime;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "profileId", column = @Column(name = "PROFILE_ID", nullable = false)),
        @AttributeOverride(name = "low_value", column = @Column(name = "LOW_VALUE", nullable = false)),
        @AttributeOverride(name = "upper_value", column = @Column(name = "UPPER_VALUE", nullable = false))})
    public EpicTleBlockBinId getId() {
        return this.id;
    }

    public void setId(EpicTleBlockBinId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROFILE_ID", nullable = false, insertable = false, updatable = false)
    public EpicTleBinProfile getEpicTleBinProfile() {
        return this.epicTleBinProfile;
    }

    public void setEpicTleBinProfile(EpicTleBinProfile epicTleBinProfile) {
        this.epicTleBinProfile = epicTleBinProfile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "DATETIME", length = 19)
    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    @Override
    public String toString() {
        try {
            return "{" + "Id:" + id.getProfileId() + ", Bin Profile:" + epicTleBinProfile.getId() + ", Date Time:" + datetime + '}';
        } catch (Exception e) {
            return "{" + "Id:" + id.getProfileId() + ", Date Time:" + datetime + '}';
        }
    }

    public String forHistory() {
        try {
            return "{" + "Id:" + id + ", Bin Profile:" + epicTleBinProfile.getId() + ", Date Time:" + datetime + '}';
        } catch (Exception e) {
            return "{" + "Id:" + id + ", Date Time:" + datetime + '}';
        }
    }

}
