package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EpicTlePortconfig generated by hbm2java
 */
@Entity
@Table(name = "EPIC_TLE_PORTCONFIG"
//    ,catalog="epictle_v5ch"
)
public class EpicTlePortconfig implements java.io.Serializable {

    private Integer sid;
    private Integer datarate;
    private Integer databits;
    private String parity;
    private Integer stopbits;
    private Integer status;
    private String description;
    private String port;

    public EpicTlePortconfig() {
    }

    public EpicTlePortconfig(Integer datarate, Integer databits, String parity, Integer stopbits, Integer status, String description, String port) {
        this.datarate = datarate;
        this.databits = databits;
        this.parity = parity;
        this.stopbits = stopbits;
        this.status = status;
        this.description = description;
        this.port = port;
    }

    @Id
    @GenericGenerator(name = "id_generator", strategy = "com.epic.tle.util.IdGenerator", parameters= {@Parameter(name="columnPram", value = "sid")})
    @GeneratedValue(generator = "id_generator")
    @Column(name = "SID", unique = true, nullable = false)
    public Integer getSid() {
        return this.sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    @Column(name = "DATARATE")
    public Integer getDatarate() {
        return this.datarate;
    }

    public void setDatarate(Integer datarate) {
        this.datarate = datarate;
    }

    @Column(name = "DATABITS")
    public Integer getDatabits() {
        return this.databits;
    }

    public void setDatabits(Integer databits) {
        this.databits = databits;
    }

    @Column(name = "PARITY", length = 5)
    public String getParity() {
        return this.parity;
    }

    public void setParity(String parity) {
        this.parity = parity;
    }

    @Column(name = "STOPBITS")
    public Integer getStopbits() {
        return this.stopbits;
    }

    public void setStopbits(Integer stopbits) {
        this.stopbits = stopbits;
    }

    @Column(name = "STATUS")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Column(name = "DESCRIPTION", length = 20)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PORT", length = 10)
    public String getPort() {
        return this.port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    @Override
    public String toString() {
        return "{" + "sid:" + sid + ", data rate:" + datarate + ", data bits:" + databits + ", parity:" + parity + ", stop bits:" + stopbits + ", status:" + status + ", description:" + description + ", port:" + port + '}';
    }

    public String forHistory() {
        return "{" + "sid:" + sid + ", data rate:" + datarate + ", data bits:" + databits + ", parity:" + parity + ", stop bits:" + stopbits + ", status:" + status + ", description:" + description + ", port:" + port + '}';
    }

}
