package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleColorFormat generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_COLOR_FORMAT"
//    ,catalog="epictle_v5ch"
)
public class EpicTleColorFormat  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleSysOperation> epicTleSysOperations = new HashSet<EpicTleSysOperation>(0);

    public EpicTleColorFormat() {
    }

	
    public EpicTleColorFormat(int code) {
        this.code = code;
    }
    public EpicTleColorFormat(int code, String description, Set<EpicTleSysOperation> epicTleSysOperations) {
       this.code = code;
       this.description = description;
       this.epicTleSysOperations = epicTleSysOperations;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleColorFormat")
    public Set<EpicTleSysOperation> getEpicTleSysOperations() {
        return this.epicTleSysOperations;
    }
    
    public void setEpicTleSysOperations(Set<EpicTleSysOperation> epicTleSysOperations) {
        this.epicTleSysOperations = epicTleSysOperations;
    }

    @Override
    public String toString() {
        return "EpicTleColorFormat{" + "code=" + code + ", description=" + description + ", epicTleSysOperations=" + epicTleSysOperations + '}';
    }




}


