package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EpicTleResponsecode generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_RESPONSECODE"
//    ,catalog="epictle_v5ch"
)
public class EpicTleResponsecode  implements java.io.Serializable {


     private String code;
     private String description;

    public EpicTleResponsecode() {
    }

    public EpicTleResponsecode(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=2)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "EpicTleResponsecode{" + "code=" + code + ", description=" + description + '}';
    }




}


