package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleAlertType generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_ALERT_TYPE"
//    ,catalog="epictle_v5ch"
)
public class EpicTleAlertType  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleAlerts> epicTleAlertses = new HashSet<EpicTleAlerts>(0);

    public EpicTleAlertType() {
    }

	
    public EpicTleAlertType(int code) {
        this.code = code;
    }
    public EpicTleAlertType(int code, String description, Set<EpicTleAlerts> epicTleAlertses) {
       this.code = code;
       this.description = description;
       this.epicTleAlertses = epicTleAlertses;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleAlertType")
    public Set<EpicTleAlerts> getEpicTleAlertses() {
        return this.epicTleAlertses;
    }
    
    public void setEpicTleAlertses(Set<EpicTleAlerts> epicTleAlertses) {
        this.epicTleAlertses = epicTleAlertses;
    }

    @Override
    public String toString() {
        return "EpicTleAlertType{" + "code=" + code + ", description=" + description + ", epicTleAlertses=" + epicTleAlertses + '}';
    }




}


