package com.epic.tle.mapping;
// Generated May 31, 2017 9:39:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EpicTleEncryptionlevles generated by hbm2java
 */
@Entity
@Table(name="EPIC_TLE_ENCRYPTIONLEVLES"
//    ,catalog="epictle_v5ch"
)
public class EpicTleEncryptionlevles  implements java.io.Serializable {


     private int code;
     private String description;
     private Set<EpicTleTerminal> epicTleTerminals = new HashSet<EpicTleTerminal>(0);

    public EpicTleEncryptionlevles() {
    }

	
    public EpicTleEncryptionlevles(int code) {
        this.code = code;
    }
    public EpicTleEncryptionlevles(int code, String description, Set<EpicTleTerminal> epicTleTerminals) {
       this.code = code;
       this.description = description;
       this.epicTleTerminals = epicTleTerminals;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", length=30)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="epicTleEncryptionlevles")
    public Set<EpicTleTerminal> getEpicTleTerminals() {
        return this.epicTleTerminals;
    }
    
    public void setEpicTleTerminals(Set<EpicTleTerminal> epicTleTerminals) {
        this.epicTleTerminals = epicTleTerminals;
    }

    @Override
    public String toString() {
        return "EpicTleEncryptionlevles{" + "code=" + code + ", description=" + description + ", epicTleTerminals=" + epicTleTerminals + '}';
    }




}


